name: Gradle Daemon Test

on:
  workflow_dispatch: # run manually from Actions tab

jobs:
  gradle-daemon:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run a Gradle build (will spawn daemons)
        run: |
          ./gradlew.bat build

      - name: List GradleDaemon processes
        shell: pwsh
        run: |
          Get-Process java | Where-Object { $_.CommandLine -like '*GradleDaemon*' } | Select-Object Id, Path, CommandLine

      - name: Kill GradleDaemon processes
        shell: cmd
        run: |
          powershell.exe -NoProfile -Command "Get-Process java | Where-Object -FilterScript { \$_.CommandLine -like '*GradleDaemon*' } | Select-Object Id, Path, CommandLine"

      - name: List GradleDaemon processes
        shell: pwsh
        run: |
          Get-Process java | Where-Object { $_.CommandLine -like '*GradleDaemon*' } | Select-Object Id, Path, CommandLine
