name: Gradle Daemon Test

on:
  workflow_dispatch: # run manually from Actions tab

jobs:
  gradle-daemon:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run a Gradle build (will spawn daemons)
        run: |
          ./gradlew.bat build

      - name: Create list-gradle-daemons.ps1
        run: |
          @'
          $procs = Get-CimInstance Win32_Process -Filter "Name='java.exe' AND CommandLine LIKE '%GradleDaemon%'"
          if ($procs) {
              foreach ($p in $procs) {
                  $path = if ($p.ExecutablePath) { $p.ExecutablePath } else { "<no path>" }
                  Write-Output ("{0} {1} {2}" -f $p.ProcessId, $path, $p.CommandLine)
              }
          } else {
              Write-Output "No GradleDaemon java processes found."
          }
          exit 0
          '@ | Set-Content -Path list-gradle-daemons.ps1 -Encoding UTF8
        shell: pwsh

      - name: Create kill-gradle-daemons.ps1
        run: |
          @'
          $procs = Get-CimInstance Win32_Process -Filter "Name='java.exe' AND CommandLine LIKE '%GradleDaemon%'"
          if ($procs) {
              foreach ($p in $procs) {
                  $pid = $p.ProcessId
                  $res = Invoke-CimMethod -InputObject $p -MethodName Terminate
                  Write-Output ("Terminated {0} -> ReturnValue {1}" -f $pid, $res.ReturnValue)
              }
          } else {
              Write-Output "No GradleDaemon java processes found."
          }
          exit 0
          '@ | Set-Content -Path kill-gradle-daemons.ps1 -Encoding UTF8
        shell: pwsh


      - name: Run list-gradle-daemons.ps1 via cmd
        shell: cmd
        run: |
          powershell.exe -NoProfile -ExecutionPolicy Bypass -File list-gradle-daemons.ps1      
          
      - name: Run kill-gradle-daemons.ps1 via cmd
        shell: cmd
        run: |
          powershell.exe -NoProfile -ExecutionPolicy Bypass -File kill-gradle-daemons.ps1

      - name: List GradleDaemon processes
        shell: pwsh
        run: |
          Get-Process java | Where-Object { $_.CommandLine -like '*GradleDaemon*' } | Select-Object Id, Path, CommandLine

      # - name: Kill GradleDaemon processes
      #   shell: cmd
      #   run: |
      #     powershell.exe -ExecutionPolicy Bypass -Command "Get-Process java | Where-Object { `$_.CommandLine -like '*GradleDaemon*' } | Select-Object Id,Path,CommandLine"

      # - name: List GradleDaemon processes
      #   shell: pwsh
      #   run: |
      #     Get-Process java | Where-Object { $_.CommandLine -like '*GradleDaemon*' } | Select-Object Id, Path, CommandLine
